### ISSUE TITLE
Sample folder: The Link field in all the examples of TDs are not arrays as the W3C document defines it.

### ISSUE THREAD

**Issue by onovo1** [thingweb/thingweb-directory#1]
According to the W3C, the link field of a TD should have an array of values. However, the examples in the samples folder show an object instead. The link field should be changed from:

"link": {
                                                                "href": "val",
                                                                "mediaType": "application/json"
}

To:

"link": [{
                                                                "href": "val",
                                                                "mediaType": "application/json"
}]

In all the samples.

**Comment by vcharpenay** [comment]
Fixed. Input/output data definitions were also not compliant with the latest W3C draft anymore. However, please note that in fact, it has no consequence on the code itself.

Since we haven’t agreed upon a way to validate TD documents within the W3C group, the Thing Directory just considers them as JSON-LD documents. It happens that the RDF representation of a JSON-LD object will be just the same regardless of whether it is wrapped by brackets or not.

You could also register the following document as a TD and the Directory will accept it, because its RDF representation is consistent with the semantics defined in the TD ontology:

```
{
  “@context”: “…”,
  “@graph”: [
    { “@id“: “:b0“, “@type”: “Interaction” },
    { “@id“: “:b1“, “interaction” : “_ :b0“ }
  ]
}
```

However, if the JSON-LD document contains no definition of a `td:Thing`, it will reject it.
